config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :contact_lists
  root to: "contact_lists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	has_many :contact_list_mappings
	has_many :contact_lists, through: :contact_list_mappings

	validates :name, presence: true
	validates :email, presence: true, uniqueness: { case_sensitive: false }
end

app/models/contact_list.rb
class ContactList < ApplicationRecord
	has_many :contact_list_mappings
	has_many :contacts, through: :contact_list_mappings

	validates :name, presence: true
end

app/models/contact_list_mapping.rb
class ContactListMapping < ApplicationRecord
	belongs_to :contact
	belongs_to :contact_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_lists_controller.rb
class ContactListsController < ApplicationController
  before_action :set_contact_list, only: [:show, :edit, :update, :destroy]

  # GET /contact_lists
  # GET /contact_lists.json
  def index
    @contact_lists = ContactList.all
  end

  # GET /contact_lists/1
  # GET /contact_lists/1.json
  def show
  end

  # GET /contact_lists/new
  def new
    @contact_list = ContactList.new
  end

  # GET /contact_lists/1/edit
  def edit
  end

  # POST /contact_lists
  # POST /contact_lists.json
  def create
    @contact_list = ContactList.new(contact_list_params)

    respond_to do |format|
      if @contact_list.save
        format.html { redirect_to @contact_list, notice: 'Contact list was successfully created.' }
        format.json { render :show, status: :created, location: @contact_list }
      else
        format.html { render :new }
        format.json { render json: @contact_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_lists/1
  # PATCH/PUT /contact_lists/1.json
  def update
    respond_to do |format|
      if @contact_list.update(contact_list_params)
        format.html { redirect_to @contact_list, notice: 'Contact list was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact_list }
      else
        format.html { render :edit }
        format.json { render json: @contact_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_lists/1
  # DELETE /contact_lists/1.json
  def destroy
    @contact_list.destroy
    respond_to do |format|
      format.html { redirect_to contact_lists_url, notice: 'Contact list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_list
      @contact_list = ContactList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_list_params
      params.require(:contact_list).permit(:name)
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  	before_action :set_contact, only: [:show, :edit, :update, :destroy]

  	def index
    	@contacts = Contact.all
  	end

  	def new
    	@contact = Contact.new
  	end
  
    def create
  		@contact= Contact.new(contact_params)
  		respond_to do |format|
	  		if @contact.save
	  			format.html { redirect_to @contact, notice: 'contact successfully created' }
	  			format.json { render :show, status: :created, location: @contact }
	  		else
	  			format.html { render :new }
	  			format.json { render json: @contact.errors, status: :unprocessable_entity}
	  		end
	  	end
  	end
    
    def edit
    end

    def update
	    respond_to do |format|
	      if @contact.update(contact_params)
	        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
	        format.json { render :show, status: :ok, location: @contact }
	      else
	        format.html { render :edit }
	        format.json { render json: @contact.errors, status: :unprocessable_entity }
	      end
	    end
    end

  	def show
  	end

  	def destroy
	  	@contact.destroy
	    respond_to do |format|
	      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
	      format.json { head :no_content }
	    end
  	end

   	private
    
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def contact_params
      params.require(:contact).permit(:name, :email, contact_list_ids: [])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_list_mappings_helper.rb
module ContactListMappingsHelper
end

app/helpers/contact_lists_helper.rb
module ContactListsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contact_lists/_form.html.erb
<%= form_with(model: contact_list, local: true) do |form| %>
  <% if contact_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact_list.errors.count, "error") %> prohibited this contact_list from being saved:</h2>

      <ul>
      <% contact_list.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_list_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contact_lists/edit.html.erb
<h1>Editing Contact List</h1>

<%= render 'form', contact_list: @contact_list %>

<%= link_to 'Show', @contact_list %> |
<%= link_to 'Back', contact_lists_path %>

app/views/contact_lists/index.html.erb
<p id="notice"><%= notice %></p>

<h3>Contact Lists</h3>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_lists.each do |contact_list| %>
      <tr>
        <td><%= contact_list.name %></td>
        <td><%= link_to 'Show', contact_list %></td>
        <td><%= link_to 'Edit', edit_contact_list_path(contact_list) %></td>
        <td><%= link_to 'Destroy', contact_list, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact List', new_contact_list_path %> |
<%= link_to 'New Contact ', new_contact_path %>

app/views/contact_lists/new.html.erb
<h1>New Contact List</h1>

<%= render 'form', contact_list: @contact_list %>

<%= link_to 'Back', contact_lists_path %>

app/views/contact_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact_list.name %>
</p>

<% @contact_list.contact_list_mappings.each do |contact_list_mapping| %>
    <li ><%= link_to contact_list_mapping.contact.name, contact_path(contact_list_mapping.contact) %></li>
<% end %>


Back To Contacts <%= link_to 'Back', contacts_path %>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>
  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>
  
  <%= form.collection_check_boxes :contact_list_ids, ContactList.all, :id, :name %>

  <div class="actions">
    <%= form.submit %>
  </div>
  
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit Contact </h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contact</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %> |
<%= link_to 'Contact List', contact_lists_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>


<%= @contact.name %>  is associated with 

<% @contact.contact_lists.each do |contact_list| %>
  <%= link_to contact_list.name, contact_list_path(contact_list) %>
<% end %>


<br> <br>
<%= link_to 'Edit', edit_contact_path(@contact) %> | <%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>